
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 15 21:25:38 CST 2021
//----------------------------------------------------

package CupYFlex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 8;
  public static final int CORCHETEDER = 15;
  public static final int CADENA = 19;
  public static final int CHAR = 18;
  public static final int DECIMAL = 17;
  public static final int BOOLT = 5;
  public static final int PISTA = 3;
  public static final int POT = 10;
  public static final int SIMMAS = 6;
  public static final int COMA = 11;
  public static final int EOF = 0;
  public static final int BOOLF = 4;
  public static final int ASTERISCO = 7;
  public static final int EXTIENDE = 2;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int ENTERO = 16;
  public static final int PARABRE = 12;
  public static final int PARCIERRA = 13;
  public static final int CORCHETEIZ = 14;
}

