
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 10 13:20:41 CST 2021
//----------------------------------------------------

package CupYFlex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 45;
  public static final int SUMASUMA = 50;
  public static final int CONTINUAR = 22;
  public static final int CORCHETEDER = 41;
  public static final int MENSAJE = 30;
  public static final int MAYOR = 59;
  public static final int KEEP = 11;
  public static final int POT = 57;
  public static final int PRIMOS = 35;
  public static final int PISTA = 8;
  public static final int LN = 73;
  public static final int LONGITUD = 29;
  public static final int NOT = 70;
  public static final int SBOOLEAN = 4;
  public static final int NOR = 68;
  public static final int ORDENAR = 27;
  public static final int VAR = 12;
  public static final int BOOLT = 10;
  public static final int IMPARES = 34;
  public static final int SALIR = 17;
  public static final int HACER = 20;
  public static final int PARA = 18;
  public static final int SDOBLE = 3;
  public static final int PARES = 33;
  public static final int COMA = 72;
  public static final int PARABRE = 38;
  public static final int BOOLF = 9;
  public static final int ENTERO = 47;
  public static final int MODULO = 56;
  public static final int PARCIERRA = 39;
  public static final int TAB = 74;
  public static final int IGUAL = 64;
  public static final int DECIMAL = 46;
  public static final int CHAR = 48;
  public static final int PUNTOYCOMA = 71;
  public static final int ASTERISCO = 53;
  public static final int SWITCH = 14;
  public static final int SENTERO = 2;
  public static final int VOID = 23;
  public static final int DIV = 55;
  public static final int ELSE = 37;
  public static final int MENOS = 54;
  public static final int MENOR = 60;
  public static final int MAS = 52;
  public static final int SCARACTER = 5;
  public static final int ARREGLO = 13;
  public static final int EOF = 0;
  public static final int MIENTRAS = 19;
  public static final int DEFAULT = 15;
  public static final int SUMARIZAR = 28;
  public static final int MENORIGUAL = 62;
  public static final int PRINCIPAL = 24;
  public static final int CORCHETEIZ = 40;
  public static final int OR = 67;
  public static final int error = 1;
  public static final int REPRODUCIR = 25;
  public static final int MASIGUAL = 49;
  public static final int IF = 36;
  public static final int ESNULO = 63;
  public static final int EXTIENDE = 7;
  public static final int UMENOS = 76;
  public static final int CASO = 16;
  public static final int ESPERAR = 26;
  public static final int LLAVECIERRA = 43;
  public static final int NOIGUAL = 58;
  public static final int CASE = 21;
  public static final int CADENA = 44;
  public static final int MAYORIGUAL = 61;
  public static final int LLAVEABRE = 42;
  public static final int ASCENDENTE = 31;
  public static final int AND = 65;
  public static final int UMINUS = 75;
  public static final int DESCENDENTE = 32;
  public static final int MENOSMENOS = 51;
  public static final int NAND = 66;
  public static final int XOR = 69;
  public static final int SCADENA = 6;
}

