
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 05 01:28:39 CST 2021
//----------------------------------------------------

package CupYFlex.Jison;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 29;
  public static final int CORCHETEDER = 19;
  public static final int DURACION = 8;
  public static final int CADENA = 22;
  public static final int IGUAL = 30;
  public static final int CHAR = 26;
  public static final int DECIMAL = 24;
  public static final int OCTAVA = 14;
  public static final int DATOS = 15;
  public static final int UMENOS = 31;
  public static final int PISTA = 10;
  public static final int LISTAS = 5;
  public static final int TIPO = 3;
  public static final int LLAVECIERRA = 21;
  public static final int NOTA = 12;
  public static final int ARABRE = 16;
  public static final int MAYOR = 28;
  public static final int NOMBRE = 4;
  public static final int EOF = 0;
  public static final int DIV = 27;
  public static final int CANAL = 9;
  public static final int error = 1;
  public static final int NUMERO = 11;
  public static final int FRECUENCIA = 13;
  public static final int IDENTIFICADOR = 23;
  public static final int ENTERO = 25;
  public static final int PARCIERRA = 17;
  public static final int CORCHETEIZ = 18;
  public static final int LISTA = 7;
  public static final int SOLICITUD = 2;
  public static final int ALEATORIA = 6;
  public static final int LLAVEABRE = 20;
}

